### ISSUE TITLE
where is the annotations files

### ISSUE THREAD

**Issue by xxxzhi** [scwangdyd/zero_shot_hoi#1]
Hi, thanks for your interesting work. But I fail to run the code cause I can't find the annotation file `instances_hico_train_hoi_seen_github'.  Where is it?

**Comment by scwangdyd** [comment]
Please download from https://drive.google.com/file/d/11e5mymZWOIc-2tf2xSoE4AqDf21qaUul/view?usp=sharing.

**Comment by xxxzhi** [comment]
Thanks for your sharing
